# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160413_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 24, 20, 46, 10, 313950, tzinfo=utc)),
        ),
    ]
